config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
            registrations: "public/registrations",
            sessions: "public/sessions",
          }
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#new_guest"
  end
  scope module: :public do
    root to: "homes#top"
    resources :posts do
      collection do
        get "drafts"
      end
      resource :favorite, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
      resources :post_hashtags, only: [:create, :destroy]
    end
    resources :hashtags, only: [:create, :show]
    resource :users do
      get ":user_id/follows" => "users#follows", as: "follows"
      get ":user_id/followers" => "users#followers", as: "followers"
      post "profile/:user_id/relation" => "relations#create", as: "relations_post"
      delete "profile/:user_id/relation" => "relations#destroy", as: "relation_delete"

      get "my_page" => "users#show"
      get "profile/:user_id" => "users#profile", as: "profile"

      post "profile/:user_id/report" => "reports#create", as: "profile_report"
      get "profile/:user_id/report/new" => "reports#new", as: "profile_reports_new"
      get "information/edit" => "users#edit"
      patch "information" => "users#update"
    end

    resources :events do
      collection do
        get "myevent"
      end
      resources :attendees, only: [:create, :show, :edit, :update, :destroy]
    end
  end

  get "/search", to: "searches#search"
  post "/chatbots", to: "chatbots#create"

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
            sessions: "admin/sessions",
          }

  namespace :admin do
    root to: "homes#top"
    resources :posts do
      resources :post_comments, only: [:destroy]
    end
    resources :hashtags, only: [:show]
    resources :users, only: [:index, :show, :edit, :update]
    resources :events, only: [:index, :show]
    resources :reports, only: [:index, :show, :update]
  end
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :attendees
  has_many :users, through: :attendees
  belongs_to :creator, class_name: "User"

  # ActiveStorageの設定
  has_one_attached :event_image

  validates :event_name, length: { minimum: 2 }
  validates :event_introduction, length: { minimum: 2 }

  #下書き、公開のenum設定
  enum event_type: { online: 0, offline: 1 }, _default: 0

  # creatorを参加者に含めない
  def attendees_for(user)
    if user.present?
      # 参加者リストから自分と投稿者を除いた参加者リストを返す
      return attendees.where.not(user: [user, creator])
    else
      return attendees
    end
  end

  # 検索用
  def self.search_content(content, method)
    if method == "perfect"
      where(event_name: content)
    elsif method == "partial"
      where("event_name LIKE ?", "%#{content}%")
    else
      all
    end
  end

  # 利用停止のUserの投稿は閲覧不可に
  scope :by_active_users, -> { joins(:creator).select("events.*, creator.user_status").where(creator: { user_status: 0 }).distinct }
  scope :upcoming, -> { where("date >= ?", Time.zone.now).order(date: :asc) }
  scope :visible, -> { by_active_users.upcoming }
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  def show
    @event = Event.find(params[:id])
    @attendee = Attendee.find_by(event_id: @event.id)
  end

  def index
    @events = Event.visible.page(params[:page]).per(8)
  end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/views/admin/events/index.html.erb
<div class="container">
  <h3 class="my-3">イベント一覧</h3>
  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
        <tr>
          <th scope="col">タイトル</th>
          <th scope="col">開催日</th>
          <th scope="col">投稿者</th>
        </tr>
      </thead>
      <tbody>
        <% @events.each do |event| %>
          <tr>
            <td>
              <h5 class="card-title"><%= link_to event.event_name, admin_event_path(event.id) %></h5>
            </td>
            <td>
              <p class="card-text"><%= event.date %></p>
            </td>
            <td>
              <p class="card-text"><%= link_to event.creator.full_name, admin_user_path(event.creator_id) %></p>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div class="pagination justify-content-center">
  <%= paginate @events %>
</div>
</div>

app/views/admin/events/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <%= render partial: 'shared/event_card', locals: { event: @event, isDetail: true } %>
      <div class="text-center">
        <%= link_to "イベント一覧に戻る", admin_events_path %>
      </div>
    </div>
  </div>
</div>