config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
            registrations: "public/registrations",
            sessions: "public/sessions",
          }
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#new_guest"
  end
  scope module: :public do
    root to: "homes#top"
    resources :posts do
      collection do
        get "drafts"
      end
      resource :favorite, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
      resources :post_hashtags, only: [:create, :destroy]
    end
    resources :hashtags, only: [:create, :show]
    resource :users do
      get ":user_id/follows" => "users#follows", as: "follows"
      get ":user_id/followers" => "users#followers", as: "followers"
      post "profile/:user_id/relation" => "relations#create", as: "relations_post"
      delete "profile/:user_id/relation" => "relations#destroy", as: "relation_delete"

      get "my_page" => "users#show"
      get "profile/:user_id" => "users#profile", as: "profile"

      post "profile/:user_id/report" => "reports#create", as: "profile_report"
      get "profile/:user_id/report/new" => "reports#new", as: "profile_reports_new"
      get "information/edit" => "users#edit"
      patch "information" => "users#update"
    end

    resources :events do
      collection do
        get "myevent"
      end
      resources :attendees, only: [:create, :show, :edit, :update, :destroy]
    end
  end

  get "/search", to: "searches#search"
  post "/chatbots", to: "chatbots#create"

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
            sessions: "admin/sessions",
          }

  namespace :admin do
    root to: "homes#top"
    resources :posts do
      resources :post_comments, only: [:destroy]
    end
    resources :hashtags, only: [:show]
    resources :users, only: [:index, :show, :edit, :update]
    resources :events, only: [:index, :show]
    resources :reports, only: [:index, :show, :update]
  end
end

app/views/shared/_chatbot.html.erb
<!-- Chat Modal -->
<div class="chat modal fade" id="chat-modal" tabindex="-1" role="dialog" aria-labelledby="chat-modal-title" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="chat-modal-title">ボットちゃん</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="chat__body modal-body">
        <div id="chat-messages" class="chat__messages" style="height: 400px; max-height: 400px; overflow-y: scroll;">
          <%# Controllerからくるデータがメッセージで表示される部分。 scriptの`$('#chat-messages').prepend(responseMessage, inputMessage);`部分 %>
        </div>
        <form id="chat-form" class="chat__form">
          <input type="text" class="form-control chat__input" id="chat-input" placeholder="聞きたい内容を入力してください。">
          <div class="input-group-append">
            <button type="submit" id="chat-btn" class="chat__submit">送る</button>
            <div class="spinner-border text-primary d-none" id="chat-loader" role="status">
              <span class="sr-only">Loading...</span>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<script>
  $(document).ready(function () {
      $('#chat-form').submit(function (event) {
        // デフォルトform eventを消す
          event.preventDefault();
          //　InputのValue（Chatbotにタイピングしたワード）を取る
          const input = $('#chat-input').val();
          // d-none: display: none → bootstrap
          // chat-btnにd-noneを追加する→ボタンを消す
          $('#chat-btn').addClass('d-none');
          // chat-loaderに設定されてるd-noneを消す→ローディングを出す
          $('#chat-loader').removeClass('d-none');

          // /chatbots (routes.rbに記述)
          // inputはcontroller.rbに記述）
          $.post('/chatbots', {input: input})
              // controllerで成功した時はこちにくる
              // data.responseにはcontrollerのactionでreturn jsonするところに記述してるデータが入る。
              .done(function (data) {
                  //     respond_to do |format|
                  //       format.json { render json: { response: response.dig("choices", 0, "message", "content") } }
                  //     end
                  // responseは結局content!
                  const response = data.response;
                  // controllerのactionから来たデータを利用してtagを作る
                  const responseMessage = '<div class="chat__message chat__message--bot"><i class="fas fa-robot chat__bot-icon"></i><p class="alert alert-success" role="alert">' + response + '</p></div>';
                  // inputは自分が送信したテキスト→メッセージのように自分のもはる
                  const inputMessage = '<div class="chat__message chat__message--user"><p class="alert alert-info" role="alert">' + input + '</p></div>';
                  // append (入れること)の逆バージョン = prepend -> jQueryのみ
                  $('#chat-messages').prepend(responseMessage, inputMessage);
                  // 自分が送信した内容をInput Tagから消す
                  $('#chat-input').val('');
                  // ローディングを消す
                  $('#chat-loader').addClass('d-none');
                  // ボタンを表示する
                  $('#chat-btn').removeClass('d-none');
              })
              // controllerで失敗した時はこちにくる
              .fail(function (xhr, status, error) {
                  console.log("Error:", error)
                  // Display input and response in chat-messages div
                  const responseMessage = '<div class="chat__message chat__message--bot alert alert-danger" role="alert"><i class="fas fa-robot chat__bot-icon"></i><p>' + error + '</p></div>';
                  const inputMessage = '<div class="chat__message chat__message--user alert alert-info" role="alert"><p>' + input + '</p></div>';

                  $('#chat-messages').prepend(responseMessage, inputMessage);
                  // Clear input field
                  $('#chat-loader').addClass('d-none');
                  $('#chat-btn').removeClass('d-none');
              })
      });
  });
</script>

app/views/shared/_event_card.html.erb
<div class="card event-card" data-turbolinks="false">
  <div class="event-card__body">
    <div class="event-card__info">
      <% if event.event_image.attached? %>
        <%= image_tag event.event_image, size: isDetail ? "400x480" : "310x180", class: isDetail ? 'detail' : "" %>
      <% else %>
        <%= image_tag 'no_image.png', size: isDetail ? "400x480" : "310x180", class: isDetail ? 'detail' : "" %>
      <% end %>
      <div class="event-card__header">
        <div class="event-card__header-top <%= "list" if isDetail == false %>">
          <% if event.event_type == "online" %>
            <span class="event-card__type event-card__type--online"><%= I18n.t("enums.event.event_type.#{event.event_type}") %></span>
          <% else %>
            <span class="event-card__type event-card__type--offline"><%= I18n.t("enums.event.event_type.#{event.event_type}") %></span>
          <% end %>
          <% if isDetail == true %>
            <h2 class="event-card__title"><%= event.event_name %></h2>
          <% else %>
            <%= link_to event.event_name, event_path(event.id), class: 'event-card__title list' %>
          <% end %></div>
        <div class="event-card__header-bottom">
          <%= link_to event.creator.full_name, profile_users_path(event.creator), class: 'event-card__author' %>
        </div>
      </div>
      <p class="event-card__introduction <%= "list" if isDetail == false %>"><%= event.event_introduction %></p>
      <% if isDetail == true %>
        <% if flash.now[:notice] =~ /https?:\/\/\S+/ %>
          <% flash.now[:notice].scan(/https?:\/\/\S+/) do |url| %>
            <p class="event-card__url">
              <strong>URL: </strong> <%= link_to url, url %>
            </p>
          <% end %>
        <% end %>
      <% end %>
    </div>
    <div class="event-card__date <%= "list" if isDetail == false %>">
      <i class="far fa-clock"></i><span data-utc-time="<%= event.date %>"></span>
    </div>
    <% if isDetail == true && event.event_type == "offline" %>
      <div class="event-card__gmap">
        <h6 class="event-card__address"><%= event.address %></h6>
        <div id="map" style="width: 100%; height: 500px;"></div>
      </div>
    <% end %>
    <div class="event-card__footer">
      <% unless isDetail %>
        <div class="event-card__participants">
          <div class="event-card__avatar-group">
            <% if event.users.length > 0 %>
              <% event.users.each do |user| %>
                <% if user.image.attached? %>
                  <%= image_tag user.image, size: "150x150", class: 'event-card__avatar' %>
                <% else %>
                  <%= image_tag 'no_image.png', size: "150x150", class: 'event-card__avatar' %>
                <% end %>
              <% end %>
            <% else %>
              <div style="height:36px"></div>
            <% end %>
          </div>
          <% unless event.users.count == 0 %>
            <div class="event-card__count">
              <%= event.users.count %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <% if isDetail && event.event_type == "offline" %>
    <div type="text/javascript">
      <script>
        function initMap(){
          let map = new google.maps.Map(document.getElementById('map'), {
            center: {lat: <%= event.latitude %>, lng: <%= event.longitude %> },
            zoom: 15
          });
          new google.maps.Marker({
            position: {lat: <%= event.latitude %>, lng: <%= event.longitude %> },
            map: map,
            title: "Your current location",
          });
        }
        var script = document.createElement('script');
        script.src = "https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API_KEY'] %>&libraries=places&callback=initMap";
        script.async = true;

        // Attach your callback function to the `window` object
        window.initMap = initMap;

        // Append the 'script' element to 'head'
        document.head.appendChild(script);
      </script>
    </div>
  <% end %>
</div>

app/views/shared/_post_card.html.erb
<article class="post-card card border-0">
  <div class="post-card__author">
    <% if post.user.image.attached? %>
      <%= image_tag post.user.image, size: "30x30", class: "post-card__avatar" %>
    <% else %>
      <%= image_tag 'no_image.png', size: "30x30", class: "post-card__avatar" %>
    <% end %>
    <%= link_to post.user.full_name, profile_users_path(post.user.id), class: 'post-card__username' %>
  </div>
  <div class="post-card__wrapper">
    <% if isDetail == false %>
      <div class="post-card__image">
        <% if post.post_image.attached? %>
          <%= image_tag post.post_image, size: "120x120" %>
        <% else %>
          <%= image_tag 'no_image.png', size: "120x120" %>
        <% end %>
      </div>
    <% end %>
    <div class="post-card__contents">
      <h4 class="<%= isDetail ? "post-card__title detail" : "post-card__title" %>">
        <% if request.fullpath.include? "drafts" %>
          <%= link_to post.title, edit_post_path(post) %>
        <% else %>
          <%= link_to post.title, post_path(post.id) %>
        <% end %>
      </h4>
      <% if isDetail %>
        <div class="markdown">
          <!--<%= toc(post.body) %>-->
          <%= markdown(post.body) %>
        </div>
      <% end %>
      <ul class="post-card__hashtag-wrapper">
        <% post.hashtags.each do |hashtag| %>
          <li class="post-card__hashtag">
            <%= link_to hashtag.hashtag_name, hashtag_path(hashtag.id) %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
  <ul class="post-card__stats">
    <li>
      <time class="post-card__date" datetime="2023-03-19"><%= post.created_at %></time>
    </li>
    <% unless request.fullpath.include? "drafts" %>
      <li id="comments-count"  class="post-card__comments" <%= "data-toggle=tooltip" unless user_signed_in? || admin_signed_in? %>  data-placement="bottom" title="コメントをするには、ログインしてください。">
        <%= render partial: 'public/post_comments/post_comments_count', locals: { post: post } %>
      </li>
      <li id="favorites-<%= post.id %>" class="post-card__likes" <%= "data-toggle=tooltip" unless user_signed_in? || admin_signed_in? %> data-placement="bottom" title="いいねをするには、ログインしてください。">
        <%= render partial: 'public/favorites/favorite', locals: { post: post } %>
      </li>
    <% end %>
  </ul>
</article>

app/views/shared/_post_comment_card.html.erb
<div class="comment-card card border-0" >
  <div class="comment-card__header">
    <div class="comment-card__author">
      <% if comment.user.image.attached? %>
        <%= image_tag comment.user.image, size: "30x30", class: "comment-card__avatar" %>
      <% else %>
        <%= image_tag 'no_image.png', size: "30x30", class: "comment-card__avatar" %>
      <% end %>
      <%= link_to comment.user.full_name, profile_users_path(comment.user.id), class: 'comment-card__username' %>
    </div>
    <div class="comment-card__createdAt">
      <%= comment.created_at %>
    </div>
  </div>
  <div class="comment-card__wrapper" >
    <div class="comment-card__contents">
      <p class="comment-card__body"><%= comment.comment%></p>
      <% if user_signed_in? %>
        <% if comment.user == current_user %>
          <div class="text-right">
            <%= link_to "削除", post_post_comment_path(post, comment), method: :delete, remote: true, data: { confirm: '本当に削除して良いですか?', cancel: 'やめる', commit: '削除する' }, title: '削除確認' %>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</div>