config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
            registrations: "public/registrations",
            sessions: "public/sessions",
          }
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#new_guest"
  end
  scope module: :public do
    root to: "homes#top"
    resources :posts do
      collection do
        get "drafts"
      end
      resource :favorite, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
      resources :post_hashtags, only: [:create, :destroy]
    end
    resources :hashtags, only: [:create, :show]
    resource :users do
      get ":user_id/follows" => "users#follows", as: "follows"
      get ":user_id/followers" => "users#followers", as: "followers"
      post "profile/:user_id/relation" => "relations#create", as: "relations_post"
      delete "profile/:user_id/relation" => "relations#destroy", as: "relation_delete"

      get "my_page" => "users#show"
      get "profile/:user_id" => "users#profile", as: "profile"

      post "profile/:user_id/report" => "reports#create", as: "profile_report"
      get "profile/:user_id/report/new" => "reports#new", as: "profile_reports_new"
      get "information/edit" => "users#edit"
      patch "information" => "users#update"
    end

    resources :events do
      collection do
        get "myevent"
      end
      resources :attendees, only: [:create, :show, :edit, :update, :destroy]
    end
  end

  get "/search", to: "searches#search"
  post "/chatbots", to: "chatbots#create"

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
            sessions: "admin/sessions",
          }

  namespace :admin do
    root to: "homes#top"
    resources :posts do
      resources :post_comments, only: [:destroy]
    end
    resources :hashtags, only: [:show]
    resources :users, only: [:index, :show, :edit, :update]
    resources :events, only: [:index, :show]
    resources :reports, only: [:index, :show, :update]
  end
end

app/models/post.rb
class Post < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  belongs_to :user
  #hashtag機能
  has_many :post_hashtags, dependent: :destroy
  has_many :hashtags, through: :post_hashtags

  #ActiveStorageの設定
  has_one_attached :post_image
  #validation
  validates :title, length: { minimum: 2 }
  validates :body, length: { minimum: 2 }

  #下書き、公開のenum設定
  enum post_status: { published: 0, draft: 1 }

  #下書き機能
  def save_draft
    self.post_status = :draft
    save(validate: false)
  end

  #利用停止のuserの投稿を閲覧不可に
  scope :published, -> { where(post_status: :published) }
  scope :by_active_users, -> { joins(:user).where(users: { user_status: 0 }) }
  scope :visible, -> { published.by_active_users }

  #いいね機能
  def favorited_by?(user)
    #favorites.exists?(user_id: user.id)
    user.present? && favorites.exists?(user_id: user.id)
  end

  #検索用
  def self.search_content(content, method)
    if method == "perfect"
      where(title: content)
    elsif method == "partial"
      where("title LIKE ?", "%#{content}%")
    else
      all
    end
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  def index
    @posts = Post.visible.page(params[:page]).per(8)

    case params[:sort]
    when "favorites"
      # @posts = @posts.order(attendee_count: :desc)
      @posts = @posts.includes(:hashtags)
        .left_joins(:favorites)
        .select("posts.*, COUNT(favorites.id) AS favorites_count")
        .group("posts.id")
        .order("favorites_count DESC")
        .visible.order(favorites_count: :desc).page(params[:page]).per(8)
    when "latest"
      @posts = @posts.order(created_at: :desc).page(params[:page]).per(8)
    end
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
    @post_hashtags = @post.hashtags
  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/views/admin/posts/index.html.erb
<div class="container">
  <h3 class="my-3">投稿一覧</h3>
  <%= link_to "いいね順", admin_posts_path(sort: :favorites), class: "btn btn-primary" %>
  <%= link_to "最新順", admin_posts_path(sort: :latest), class: "btn btn-primary" %>
  <div class="row">
    <div class="col">
      <div class="table-responsive">
        <table class="table table-hover">
          <thead>
            <tr>
              <th scope="col">タイトル</th>
              <th scope="col">投稿者</th>
              <th scope="col">投稿日</th>
              <th scope="col">いいね</th>
              <th scope="col">コメント数</th>
            </tr>
          </thead>
          <tbody>
            <% @posts.each do |post| %>
              <tr>
                <td><%= link_to post.title, admin_post_path(post.id) %></td>
                <td><%= link_to post.user.full_name, admin_user_path(post.user.id) %></td>
                <td><%= post.created_at.in_time_zone('Tokyo').strftime('%Y-%m-%d %H:%M:%S') %></td>
                <td><%= post.favorites.count %>件</td>
                <td><%= post.post_comments.count %>件</td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
<div class="pagination justify-content-center">
  <%= paginate @posts %>
</div>

app/views/admin/posts/show.html.erb
<div class="container-fluid">
  <div class="row justify-content-center">
    <div class="col-lg-6 col-md-8 col-sm-10">
      <div class="card mb-3">
        <div class="card-header">
          <h2>投稿詳細</h2>
        </div>
        <div class="card-body">
          <h4 class="card-title mb-3"><%= @post.title %></h4>
          <p class="card-text mb-3"><%= @post.body %></p>
          <div class="d-flex flex-wrap mb-3">
            <% @post.hashtags.each do |hashtag| %>
              <%= link_to hashtag.hashtag_name, admin_hashtag_path(hashtag.id) %>
            <% end %>
          </div>
          <p class="card-text">投稿者：<%= link_to @post.user.full_name, admin_user_path(@post.user.id) %></p>
          <hr>
          <div class="d-flex justify-content-between align-items-center">
            <%= @post.favorites.count %>like
            <span>コメント件数：<%= @post.post_comments.count %></span>
          </div>
          <hr>
          <div class="comment-box">
            <% @post.post_comments.each do |post_comment| %>
              <div class="card mb-3">
                <div class="card-body">
                  <p class="card-text"><%= post_comment.user.full_name %>:<%= post_comment.comment %></p>
                  <p class="card-text text-muted"><small><%= post_comment.created_at.strftime('%Y/%m/%d %H:%M:%S') %></small></p>
                  <div class="text-right">
                    <%= link_to "削除", admin_post_post_comment_path(@post, post_comment), method: :delete, class: 'btn btn-danger btn-sm' %>
                  </div>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>