config/routes.rb
Rails.application.routes.draw do
  resources :blogs
  # 顧客用
  # URL /customers/sign_in ...
  devise_for :users, skip: [:passwords], controllers: {
            registrations: "public/registrations",
            sessions: "public/sessions",
          }
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#new_guest"
  end
  scope module: :public do
    root to: "homes#top"
    resources :posts do
      collection do
        get "drafts"
      end
      resource :favorite, only: [:create, :destroy]
      resources :post_comments, only: [:create, :destroy]
      resources :post_hashtags, only: [:create, :destroy]
    end
    resources :hashtags, only: [:create, :show]
    resource :users do
      get ":user_id/follows" => "users#follows", as: "follows"
      get ":user_id/followers" => "users#followers", as: "followers"
      post "profile/:user_id/relation" => "relations#create", as: "relations_post"
      delete "profile/:user_id/relation" => "relations#destroy", as: "relation_delete"

      get "my_page" => "users#show"
      get "profile/:user_id" => "users#profile", as: "profile"

      post "profile/:user_id/report" => "reports#create", as: "profile_report"
      get "profile/:user_id/report/new" => "reports#new", as: "profile_reports_new"
      get "information/edit" => "users#edit"
      patch "information" => "users#update"
    end

    resources :events do
      collection do
        get "myevent"
      end
      resources :attendees, only: [:create, :show, :edit, :update, :destroy]
    end
  end

  get "/search", to: "searches#search"
  post "/chatbots", to: "chatbots#create"

  # 管理者用
  # URL /admin/sign_in ...
  devise_for :admin, skip: [:registrations, :passwords], controllers: {
            sessions: "admin/sessions",
          }

  namespace :admin do
    root to: "homes#top"
    resources :posts do
      resources :post_comments, only: [:destroy]
    end
    resources :hashtags, only: [:show]
    resources :users, only: [:index, :show, :edit, :update]
    resources :events, only: [:index, :show]
    resources :reports, only: [:index, :show, :update]
  end
end

app/views/layouts/_footer.html.erb
<footer class="fixed-bottom text-center" id="main-footer">
  <div class="container">
    <p>&copy; Narita Airi <%= Date.today.year %></p>
    <a href="https://airi-introduction.vercel.app/" target="_blank">About Narita Airi Introduction ▶︎ ▷ ▶︎ ▷</a>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="position-fixed fixed-top" id="main-header">
  <nav class="navbar navbar-expand-lg navbar-light m-1">
    <% if request.fullpath.include? "admin" %>
      <%= link_to image_tag('together.png', size: '150x40'), admin_root_path, class: 'navbar-brand' %>
    <% else  %>
      <%= link_to image_tag('together.png', size: '150x40'), root_path, class: 'navbar-brand' %>
    <% end  %>
    <button id="header-navbar-toggler" class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <% if request.fullpath.include? "admin" %>
            <%= link_to 'POST', admin_posts_path, class: 'nav-link' %>
          <% else  %>
            <%= link_to 'POST', posts_path, class: 'nav-link' %>
          <% end  %>
        </li>
        <li class="nav-item">
          <% if request.fullpath.include? "admin" %>
            <%= link_to 'EVENT', admin_events_path, class: 'nav-link' %>
          <% else  %>
            <%= link_to 'EVENT', events_path, class: 'nav-link' %>
          <% end  %>
        </li>
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to 'MY PAGE', my_page_users_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'LOGOUT', destroy_user_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% elsif admin_signed_in? %>
          <li class="nav-item">
            <%= link_to 'USERS', admin_root_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'LOGOUT', destroy_admin_session_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'SIGNUP', new_user_registration_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'LOGIN', new_user_session_path, class: 'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'GUEST', users_guest_sign_in_path, method: :post, class: 'nav-link' %>
          </li>
        <% end %>
        <li class="nav-item">
          <%= render 'layouts/search' %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/_search.html.erb
<div class="search-form">
  <%= form_with url: search_path, method: :get, class: "search-form__form" do |f| %>
    <div class="search-form__select-wrapper">
      <%= f.select :model, options_for_select({ "全てから探す" => nil, "User" => "user", "Post" => "post", "Event" => "event", "Hashtag" => "hashtag" }, { :class => 'my_style_class' }) %>
      <%= f.select :method, options_for_select({ "部分一致" => "partial" , "完全一致" => "perfect"}, { :class => 'my_style_class' }) %>
    </div>
    <%= f.text_field :content, class: "search-form__input" %>
    <%= f.button :submit, class: "search-form__submit" do %>
      <i class="fas fa-search"></i>
    <% end %>
  <% end %>
</div>

app/views/layouts/_splash-logo.html.erb
<div id="splash">
  <div id="splash_logo">
    <div class="bouncing-loader">
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <!-- Google tag (gtag.js) -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-1SDCMF5414"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'G-1SDCMF5414');
    </script>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="<%= image_path("favicon.ico") %>" rel="shortcut icon" type="image/x-icon" />
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application' %>
    <%= display_meta_tags(default_meta_tags)%>
  </head>
  <body>
    <%= render 'layouts/splash-logo' %>
    <%= render 'layouts/header' %>
    <main role="main flex-grow-1" id="main-content">
      <%= yield %>
    </main>
    <%= render 'layouts/footer' %>
    <%= render 'shared/chatbot' %>
    <button type="button" class="chatbot-btn" data-toggle="modal" data-target="#chat-modal">
      <i class="fas fa-robot" data-toggle=tooltip data-placement="bottom" title="ボットと遊ぶ！"></i>
    </button>
  </body>
</html>